language: go

go:
  - 1.8

before_install:
# Coverage tools
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge

- echo Branch is ${TRAVIS_BRANCH} and Tag is $TRAVIS_TAG

# Install gcloud, for integration tests.
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
- source "${HOME}/google-cloud-sdk/path.bash.inc"

# Install test credentials.
# Note that anyone with github ACLs to push to a branch can hack .travis.yml
# and discover these credentials in the travis logs.
- if [[ -n "$TEST_SERVICE_ACCOUNT_mlab_testing" ]] ; then
  echo $TEST_SERVICE_ACCOUNT_mlab_testing | base64 -d > travis-testing.key ;
  gcloud auth activate-service-account --key-file=travis-testing.key ;

script:
# TODO: set up test coverage
- go test -v -run Get
- go test -v -run Read
- go test -v -run Should
- go test -v -run Split
- go test -v -run Cal
