language: go

go:
  - 1.8

script:
# TODO: set up test coverage
- go test -v -run Get
- go test -v -run Read
- go test -v -run Should
<<<<<<< HEAD
<<<<<<< HEAD
- go test -v -run Split

=======
- go test -v -run Cal
>>>>>>> efbaa4e... Update .travis.yml
=======
- go test -v -run Split
- go test -v -run Cal
>>>>>>> 21efc046cc4046405b3cf72b29345f27efcd3abb
