# Travis configuration for etl-embargo.

language: go

go:
  - 1.8

script:	 script:
-# TODO: set up test coverage	+# To start, run all the tests.
- go test -v -run Get
- go test -v -run Read
- go test -v -run Should	
- go test -v -run Split	
- go test -v -run Cal
