language: go

go:
  - 1.8

script:
# TODO: set up test coverage
- go test -v -run Get
- go test -v -run Read
- go test -v -run Should
<<<<<<< HEAD
- go test -v -run Split

=======
- go test -v -run Cal
>>>>>>> efbaa4e... Update .travis.yml
